# Generated by Django 4.0.5 on 2022-07-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('descricao', models.TextField(default='Nova loja')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(upload_to='produtos/%Y/%m/%d/%H/%M'),
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.loja'),
        ),
    ]
