# Generated by Django 4.0.5 on 2022-07-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_loja_alter_produto_imagem_produto_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.loja'),
        ),
    ]
