# Generated by Django 4.0.5 on 2022-07-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_produto_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('customizacao', models.TextField()),
                ('produto', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='login.produto')),
            ],
        ),
    ]
