# Generated by Django 4.0.5 on 2022-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.FileField(upload_to='produtos/'),
        ),
    ]
